# Tensor explained
## What is a Tensor?
* a1=[5] is a scalar.
* a2= [5,6,7,8] is a vector.
* a3= [[2,3,4],[3,5,6]] is a Matrix. <br>

| Indexes required | Computer science | Mathematics |
| --- | --- | --- |
| 0 | number | scalar |
|1 |array |vector |
|2 | 2d-array| matrix|
| n| nd-array|nd tensor |

* a1 is a 0 dimensional tensor
* a2 is a 1 dimensional tensor
* a3 is a 2 dimensional tensor
* A nd-array will be n dimensional tensor <br>

A tensor is the primary data structure used by neural networks. Tensors and nd-arrays are the same thing.

## Rank, Axes and Shape for a tensor
<b>Rank: </b> <br>
The rank of a tensor refers to the number of dimensions present within the tensor. Suppose we are told that we have a rank-2 tensor. This means all of the following:

* We have a matrix
* We have a 2d-array
* We have a 2d-tensor <br>
A tensor's rank tells us how many indexes are needed to refer to a specific element within the tensor. <br>

<b> Axes: </b><br>
If we have a tensor, and we want to refer to a specific dimension, we use the word axis in deep learning. An axis of a tensor is a specific dimension of a tensor.

<b> Shape: </b><br>
The shape of a tensor is determined by the length of each axis, so if we know the shape of a given tensor, then we know the length of each axis, and this tells us how many indexes are available along each axis. The shape of a tensor gives us the length of each axis of the tensor.

In [5]:
dd = [
[1,2,3],
[4,5,6],
[7,8,9]
]

In [7]:
t = torch.tensor(dd)

In [10]:
t.shape

torch.Size([3, 3])

In [11]:
type(t)

torch.Tensor

In [1]:
import torch

In [2]:
print(torch.__version__)

1.3.1


In [3]:
torch.cuda.is_available()

True

In [4]:
torch.version.cuda

'10.1'

In [3]:
x = torch.rand(3, 3)
print(x)

tensor([[0.6221, 0.6791, 0.2923],
        [0.5998, 0.2664, 0.2294],
        [0.4571, 0.0359, 0.0180]])


In [4]:
x = torch.zeros(3, 3)
print(x)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])


In [4]:
a = torch.ones(5)
print(a)

tensor([1., 1., 1., 1., 1.])


In [21]:
x = torch.Tensor(3, 3)
print(x)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])


In [22]:
x = torch.tensor([[1,3], [5, 7]])
x

tensor([[1, 3],
        [5, 7]])

# Tensor vs numpy

In [23]:
import numpy as np
import time

In [25]:
n = 6000

m1 = np.random.rand(n,n).astype(np.float32)
m2 = np.random.rand(n,n).astype(np.float32)

In [26]:
start = time.time()
result = m1.dot(m2)
end = time.time()

print("Time for numpy operation  : ",(end-start))

Time for numpy operation  :  2.3479199409484863


In [27]:
m3 = torch.rand(n,n).cuda()
m4 = torch.rand(n,n).cuda()

start = time.time()
result = torch.mm(m3,m4)
end = time.time()

print("Time for tensor operation : ",(end-start))

Time for tensor operation :  0.4781014919281006


In [31]:
type(m1)

numpy.ndarray

In [30]:
type(m3)

torch.Tensor

In [32]:
m1 = torch.from_numpy(m1) # Converting numpy to tensor
m2 = torch.from_numpy(m2)

start = time.time()
result = torch.mm(m1,m2)
end = time.time()

print("Time for tensor operation : ",(end-start))

Time for tensor operation :  1.6945767402648926


In [33]:
type(m1)

torch.Tensor

In [34]:
m3 = m3.cpu().data.numpy() # Converting tensor to numpy
m4 = m4.cpu().data.numpy()

start = time.time()
result = m3.dot(m4)
end = time.time()

print("Time for tensor operation : ",(end-start))

Time for tensor operation :  2.3241584300994873


In [35]:
type(m3)

numpy.ndarray

# Reference
## https://deeplizard.com/learn/video/v5cngxo4mIg